### ISSUE TITLE
Remove rows with null values in any columns

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac-regression-vbm#52]
Please provide a sample inputspec.json with null values in each of "string", "number" and "boolean" columns. I can use this to modify the code as needed.

**Comment by pixelsaurus** [comment]
Please see: https://github.com/trendscenter/coinstac-regression-vbm/blob/master/compspec.json#L57

**Comment by pixelsaurus** [comment]
You should be able to modify any value here for testing purposes: https://github.com/trendscenter/coinstac-regression-vbm/blob/master/test/inputspec.json#L6

**Comment by hvgazula** [comment]
@spanta28 I just spoke to @rssk and this filtering of rows will null values (with feedback to the user) in any columns is already being done on the UI. So, we don't see a need for handling this in the computation code again. Please close this issue if you agree.
